# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shipyard < Formula
  desc "Point an agent at a repo + task and run an end-to-end ship pipeline"
  homepage "https://github.com/edihasaj/shipyard"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/edihasaj/shipyard/releases/download/v0.1.0/shipyard_darwin_amd64.tar.gz"
      sha256 "ba4d80e754909cd706552835bd261a2223f62e6ae75d3a8842ce916b3089b782"

      def install
        bin.install "shipyard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/edihasaj/shipyard/releases/download/v0.1.0/shipyard_darwin_arm64.tar.gz"
      sha256 "b64b21a627ad81173c713cf62561e9e4e9ebd09a19b669443226dc09a6a0304b"

      def install
        bin.install "shipyard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/edihasaj/shipyard/releases/download/v0.1.0/shipyard_linux_amd64.tar.gz"
      sha256 "59e7d05735b58f5698270013f4fe3940489f25660f4b83b2b17e8adfebe6220f"
      def install
        bin.install "shipyard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/edihasaj/shipyard/releases/download/v0.1.0/shipyard_linux_arm64.tar.gz"
      sha256 "6d03f84bb142a5af21fd4bd76701ef7b6d998a114b937a239560b6efb54279bf"
      def install
        bin.install "shipyard"
      end
    end
  end

  test do
    system "#{bin}/shipyard", "--version"
  end
end
