# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shipyard < Formula
  desc "Point an agent at a repo + task and run an end-to-end ship pipeline"
  homepage "https://github.com/edihasaj/shipyard"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/edihasaj/shipyard/releases/download/v0.2.1/shipyard_darwin_amd64.tar.gz"
      sha256 "be8608a197bc575a2db73bdd8cfa467d99d7ad01f5f918abdc62a5d6625cebf2"

      def install
        bin.install "shipyard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/edihasaj/shipyard/releases/download/v0.2.1/shipyard_darwin_arm64.tar.gz"
      sha256 "f08eb404deec8f2c03acf59b4d77961dae3e81f084285b2b236954fb579ba2a9"

      def install
        bin.install "shipyard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/edihasaj/shipyard/releases/download/v0.2.1/shipyard_linux_amd64.tar.gz"
      sha256 "49536cc871887841f8bb87baaf66620038587b70a54d6c44c063fb33060c2e26"
      def install
        bin.install "shipyard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/edihasaj/shipyard/releases/download/v0.2.1/shipyard_linux_arm64.tar.gz"
      sha256 "194401b385bb07addb0e50d3c9c8316954607a9509d9224023bb8dd2412733c7"
      def install
        bin.install "shipyard"
      end
    end
  end

  test do
    system "#{bin}/shipyard", "--version"
  end
end
