# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vmlab < Formula
  desc "Transport-agnostic orchestrator for cross-OS verify loops."
  homepage "https://github.com/edihasaj/vmlab"
  version "0.2.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/edihasaj/vmlab/releases/download/v0.2.6/vmlab_0.2.6_darwin_x86_64.tar.gz"
      sha256 "f9d6a297f9ecc5a1f473e6ffe5324b58df9922c5589a24b1cf8284b270ba61b1"

      define_method(:install) do
        bin.install "vmlab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/edihasaj/vmlab/releases/download/v0.2.6/vmlab_0.2.6_darwin_arm64.tar.gz"
      sha256 "8d59830d15c76ee5e10f00ab65b3abc3b370bcfd94bba013ab6e09b79994d9e5"

      define_method(:install) do
        bin.install "vmlab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/edihasaj/vmlab/releases/download/v0.2.6/vmlab_0.2.6_linux_x86_64.tar.gz"
      sha256 "7b0ba86c31822dbc5dc608cf2acc62f82418683bde0b4d1ae1e0b08529831d03"
      define_method(:install) do
        bin.install "vmlab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/edihasaj/vmlab/releases/download/v0.2.6/vmlab_0.2.6_linux_arm64.tar.gz"
      sha256 "1aef9e9d4c0681fbcab77055cd99af04f54c8fa0d2c845226c2421cc71c276cf"
      define_method(:install) do
        bin.install "vmlab"
      end
    end
  end

  test do
    system "#{bin}/vmlab", "--version"
  end
end
