# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vmlab < Formula
  desc "Transport-agnostic orchestrator for cross-OS verify loops."
  homepage "https://github.com/edihasaj/vmlab"
  version "0.3.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/edihasaj/vmlab/releases/download/v0.3.4/vmlab_0.3.4_darwin_x86_64.tar.gz"
      sha256 "aff46708a81255ee7dfa8d7a60043bf948e07e7e7a2291be443220e4386761ba"

      define_method(:install) do
        bin.install "vmlab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/edihasaj/vmlab/releases/download/v0.3.4/vmlab_0.3.4_darwin_arm64.tar.gz"
      sha256 "56a667826bfebb13083babcbba4420374c241126ef88ead47548c9e3e10690f5"

      define_method(:install) do
        bin.install "vmlab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/edihasaj/vmlab/releases/download/v0.3.4/vmlab_0.3.4_linux_x86_64.tar.gz"
      sha256 "3b93a034b8c9c533be4da6aa4038b529db912473854837e17fc56a1a45d4fc16"
      define_method(:install) do
        bin.install "vmlab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/edihasaj/vmlab/releases/download/v0.3.4/vmlab_0.3.4_linux_arm64.tar.gz"
      sha256 "17e0d12be493a1d0c381375de09720ec22c979269d03ec60a46674bcd23462e6"
      define_method(:install) do
        bin.install "vmlab"
      end
    end
  end

  test do
    system "#{bin}/vmlab", "--version"
  end
end
